[package]
name = "armillary"
version = "0.50.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
clap = { version = "4.4.8", features = ["derive"] }
serde = { version = "1.0.219", features = ["serde_derive"] }

[dependencies.stardust-xr-fusion]
version = "0.51.0"
git = "https://github.com/StardustXR/core.git"
branch = "refactor/strongipc"

[dependencies.stardust-xr-asteroids]
version = "0.51.0"
git = "https://github.com/StardustXR/asteroids.git"
branch = "refactor/strongipc"
